language: android
jdk:
  - oraclejdk8

#sudo: required

notifications:
  email:
    recipients:
      - shk.schneider@gmail.com
    on_sucess: change
    on_failure: always

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository

before_script:
  - env
script:
  - bash gradlew clean assembleDebug -PdisablePreDex

before_install:
  - echo y | sdkmanager "ndk-bundle"
