language: android
jdk:
  - oraclejdk8

sudo: required

notifications:
  email:
    recipients:
      - shk.schneider@gmail.com
    on_sucess: change
    on_failure: always

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.3
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - bash gradlew assembleDebug -PdisablePreDex
