package me.shkschneider.skeleton.android.provider

import android.content.pm.PackageManager
import androidx.annotation.RequiresApi
import me.shkschneider.skeleton.android.os.AndroidHelper
import me.shkschneider.skeleton.android.app.ApplicationHelper

// <http://developer.android.com/reference/android/content/pm/PackageManager.html>
sealed class AndroidFeature(val name: String) {

    // Useless: only used to keep track of new features
    @RequiresApi(AndroidHelper.API_26)
    object ActivitiesOnSecondaryDisplays : AndroidFeature(PackageManager.FEATURE_ACTIVITIES_ON_SECONDARY_DISPLAYS)
    object AppWidgets : AndroidFeature(PackageManager.FEATURE_APP_WIDGETS)
    object AudioLowLatency : AndroidFeature(PackageManager.FEATURE_AUDIO_LOW_LATENCY)
    object AudioOutput : AndroidFeature(PackageManager.FEATURE_AUDIO_OUTPUT)
    object AudioPro : AndroidFeature(PackageManager.FEATURE_AUDIO_PRO)
    @RequiresApi(AndroidHelper.API_26)
    object Autofill : AndroidFeature(PackageManager.FEATURE_AUTOFILL)
    object Automotive : AndroidFeature(PackageManager.FEATURE_AUTOMOTIVE)
    object Backup : AndroidFeature(PackageManager.FEATURE_BACKUP)
    object Bluetooth : AndroidFeature(PackageManager.FEATURE_BLUETOOTH)
    object BluetoothLe : AndroidFeature(PackageManager.FEATURE_BLUETOOTH_LE)
    object Camera : AndroidFeature(PackageManager.FEATURE_CAMERA)
    object CameraAny : AndroidFeature(PackageManager.FEATURE_CAMERA_ANY)
    @RequiresApi(AndroidHelper.API_28)
    object CameraAr : AndroidFeature(PackageManager.FEATURE_CAMERA_AR)
    object CameraAutofocus : AndroidFeature(PackageManager.FEATURE_CAMERA_AUTOFOCUS)
    object CameraCapibilityManualPostProcessing : AndroidFeature(PackageManager.FEATURE_CAMERA_CAPABILITY_MANUAL_POST_PROCESSING)
    object CameraCapicilityManualSensor : AndroidFeature(PackageManager.FEATURE_CAMERA_CAPABILITY_MANUAL_SENSOR)
    object CameraCapabilityRaw : AndroidFeature(PackageManager.FEATURE_CAMERA_CAPABILITY_RAW)
    object CameraExternal : AndroidFeature(PackageManager.FEATURE_CAMERA_EXTERNAL)
    object CameraFlash : AndroidFeature(PackageManager.FEATURE_CAMERA_FLASH)
    object CameraFront : AndroidFeature(PackageManager.FEATURE_CAMERA_FRONT)
    object CameraLevelFull : AndroidFeature(PackageManager.FEATURE_CAMERA_LEVEL_FULL)
    @RequiresApi(AndroidHelper.API_28)
    object CompanionDeviceSetup : AndroidFeature(PackageManager.FEATURE_COMPANION_DEVICE_SETUP)
    object ConnectionService : AndroidFeature(PackageManager.FEATURE_CONNECTION_SERVICE)
    object ConsumerIr : AndroidFeature(PackageManager.FEATURE_CONSUMER_IR)
    object DeviceAdmin : AndroidFeature(PackageManager.FEATURE_DEVICE_ADMIN)
    @RequiresApi(AndroidHelper.API_26)
    object Embedded : AndroidFeature(PackageManager.FEATURE_EMBEDDED)
    @RequiresApi(AndroidHelper.API_24)
    object Ethermet : AndroidFeature(PackageManager.FEATURE_ETHERNET)
    @RequiresApi(AndroidHelper.API_29)
    object Face : AndroidFeature(PackageManager.FEATURE_FACE)
    object Faketouch : AndroidFeature(PackageManager.FEATURE_FAKETOUCH)
    object FaketouchMultitouchDistinct : AndroidFeature(PackageManager.FEATURE_FAKETOUCH_MULTITOUCH_DISTINCT)
    object FaketouchMultitouchJazzhand : AndroidFeature(PackageManager.FEATURE_FAKETOUCH_MULTITOUCH_JAZZHAND)
    object Fingerprint : AndroidFeature(PackageManager.FEATURE_FINGERPRINT)
    @RequiresApi(AndroidHelper.API_24)
    object FreeformWindowManagement : AndroidFeature(PackageManager.FEATURE_FREEFORM_WINDOW_MANAGEMENT)
    object Gamepad : AndroidFeature(PackageManager.FEATURE_GAMEPAD)
    object HifiSensors : AndroidFeature(PackageManager.FEATURE_HIFI_SENSORS)
    object HomeScreen : AndroidFeature(PackageManager.FEATURE_HOME_SCREEN)
    object InputMethods : AndroidFeature(PackageManager.FEATURE_INPUT_METHODS)
    @RequiresApi(AndroidHelper.API_29)
    object IpsecTunnels : AndroidFeature(PackageManager.FEATURE_IPSEC_TUNNELS)
    @RequiresApi(AndroidHelper.API_29)
    object Iris : AndroidFeature(PackageManager.FEATURE_IRIS)
    object Leanback : AndroidFeature(PackageManager.FEATURE_LEANBACK)
    @RequiresApi(AndroidHelper.API_26)
    object LeanbackOnly : AndroidFeature(PackageManager.FEATURE_LEANBACK_ONLY)
    object LiveTv : AndroidFeature(PackageManager.FEATURE_LIVE_TV)
    object LiveWallpaper : AndroidFeature(PackageManager.FEATURE_LIVE_WALLPAPER)
    object Location : AndroidFeature(PackageManager.FEATURE_LOCATION)
    object LocationGps : AndroidFeature(PackageManager.FEATURE_LOCATION_GPS)
    object LocationNetwork : AndroidFeature(PackageManager.FEATURE_LOCATION_NETWORK)
    object ManagedUsers : AndroidFeature(PackageManager.FEATURE_MANAGED_USERS)
    object Microphone : AndroidFeature(PackageManager.FEATURE_MICROPHONE)
    object Midi : AndroidFeature(PackageManager.FEATURE_MIDI)
    object Nfc : AndroidFeature(PackageManager.FEATURE_NFC)
    @RequiresApi(AndroidHelper.API_29)
    object NfcBeam : AndroidFeature(PackageManager.FEATURE_NFC_BEAM)
    object NfcHostCardEmulation : AndroidFeature(PackageManager.FEATURE_NFC_HOST_CARD_EMULATION)
    @RequiresApi(AndroidHelper.API_24)
    object NfcHostCardEmulationNfcf : AndroidFeature(PackageManager.FEATURE_NFC_HOST_CARD_EMULATION_NFCF)
    @RequiresApi(AndroidHelper.API_29)
    object NfcHostCardEmulationEse : AndroidFeature(PackageManager.FEATURE_NFC_OFF_HOST_CARD_EMULATION_ESE)
    @RequiresApi(AndroidHelper.API_29)
    object NfsOffHostCardEmulationUicc : AndroidFeature(PackageManager.FEATURE_NFC_OFF_HOST_CARD_EMULATION_UICC)
    object OpenglesExtensionPack : AndroidFeature(PackageManager.FEATURE_OPENGLES_EXTENSION_PACK)
    @RequiresApi(AndroidHelper.API_27)
    object Pc : AndroidFeature(PackageManager.FEATURE_PC)
    @RequiresApi(AndroidHelper.API_24)
    object PictureInPicture : AndroidFeature(PackageManager.FEATURE_PICTURE_IN_PICTURE)
    object Printing : AndroidFeature(PackageManager.FEATURE_PRINTING)
    @RequiresApi(AndroidHelper.API_27)
    object RawLow : AndroidFeature(PackageManager.FEATURE_RAM_LOW)
    @RequiresApi(AndroidHelper.API_27)
    object RamNormal : AndroidFeature(PackageManager.FEATURE_RAM_NORMAL)
    object ScreenLandscape : AndroidFeature(PackageManager.FEATURE_SCREEN_LANDSCAPE)
    object ScreenPortrait : AndroidFeature(PackageManager.FEATURE_SCREEN_PORTRAIT)
    object SecurelyRemovesUsers : AndroidFeature(PackageManager.FEATURE_SECURELY_REMOVES_USERS)
    @RequiresApi(AndroidHelper.API_29)
    object SecureLockScreen : AndroidFeature(PackageManager.FEATURE_SECURE_LOCK_SCREEN)
    object SensorAccelerometer : AndroidFeature(PackageManager.FEATURE_SENSOR_ACCELEROMETER)
    object SensorAmbientTemperature : AndroidFeature(PackageManager.FEATURE_SENSOR_AMBIENT_TEMPERATURE)
    object SensorBarometer : AndroidFeature(PackageManager.FEATURE_SENSOR_BAROMETER)
    object SensorCompass : AndroidFeature(PackageManager.FEATURE_SENSOR_COMPASS)
    object SensorGyroscope : AndroidFeature(PackageManager.FEATURE_SENSOR_GYROSCOPE)
    object SensorHeartRate : AndroidFeature(PackageManager.FEATURE_SENSOR_HEART_RATE)
    object SensorHeartRateEcg : AndroidFeature(PackageManager.FEATURE_SENSOR_HEART_RATE_ECG)
    object SensorLight : AndroidFeature(PackageManager.FEATURE_SENSOR_LIGHT)
    object SensorProximity : AndroidFeature(PackageManager.FEATURE_SENSOR_PROXIMITY)
    object SensorRelativeHumidity : AndroidFeature(PackageManager.FEATURE_SENSOR_RELATIVE_HUMIDITY)
    object SensorStepCounter : AndroidFeature(PackageManager.FEATURE_SENSOR_STEP_COUNTER)
    object SensorStepDetector : AndroidFeature(PackageManager.FEATURE_SENSOR_STEP_DETECTOR)
    object Sip : AndroidFeature(PackageManager.FEATURE_SIP)
    object SipVoip : AndroidFeature(PackageManager.FEATURE_SIP_VOIP)
    @RequiresApi(AndroidHelper.API_28)
    object StrongboxKeystore : AndroidFeature(PackageManager.FEATURE_STRONGBOX_KEYSTORE)
    object Telephony : AndroidFeature(PackageManager.FEATURE_TELEPHONY)
    object TelephonyCdma : AndroidFeature(PackageManager.FEATURE_TELEPHONY_CDMA)
    @RequiresApi(AndroidHelper.API_28)
    object TelephonyEuicc : AndroidFeature(PackageManager.FEATURE_TELEPHONY_EUICC)
    object TelephonyGsm : AndroidFeature(PackageManager.FEATURE_TELEPHONY_GSM)
    @RequiresApi(AndroidHelper.API_29)
    object TelephonyIms : AndroidFeature(PackageManager.FEATURE_TELEPHONY_IMS)
    @RequiresApi(AndroidHelper.API_28)
    object TelephonyMbms : AndroidFeature(PackageManager.FEATURE_TELEPHONY_MBMS)
    @Suppress("DEPRECATION")
    @Deprecated("Deprecated in Android.", ReplaceWith("FEATURE_LEANBACK"))
    object Television : AndroidFeature(PackageManager.FEATURE_TELEVISION)
    object Touchscreen : AndroidFeature(PackageManager.FEATURE_TOUCHSCREEN)
    object TouchscreenMultitouch : AndroidFeature(PackageManager.FEATURE_TOUCHSCREEN_MULTITOUCH)
    object TouchscreenMultitouchDistinct : AndroidFeature(PackageManager.FEATURE_TOUCHSCREEN_MULTITOUCH_DISTINCT)
    object TouchscreenMultitouchJazzhand : AndroidFeature(PackageManager.FEATURE_TOUCHSCREEN_MULTITOUCH_JAZZHAND)
    object UsbAccessory : AndroidFeature(PackageManager.FEATURE_USB_ACCESSORY)
    object UsbHost : AndroidFeature(PackageManager.FEATURE_USB_HOST)
    object VerifiedBoot : AndroidFeature(PackageManager.FEATURE_VERIFIED_BOOT)
    @RequiresApi(AndroidHelper.API_26)
    object VrHeadtracking : AndroidFeature(PackageManager.FEATURE_VR_HEADTRACKING)
    @RequiresApi(AndroidHelper.API_24)
    @Suppress("DEPRECATION")
    @Deprecated("Deprecated in Android.", ReplaceWith("FEATURE_VR_MODE_HIGH_PERFORMANCE"))
    object VrMode : AndroidFeature(PackageManager.FEATURE_VR_MODE)
    @RequiresApi(AndroidHelper.API_24)
    object BrModeHightPerformance : AndroidFeature(PackageManager.FEATURE_VR_MODE_HIGH_PERFORMANCE)
    @RequiresApi(AndroidHelper.API_26)
    object VulkanHardwareCompute : AndroidFeature(PackageManager.FEATURE_VULKAN_HARDWARE_COMPUTE)
    @RequiresApi(AndroidHelper.API_24)
    object VulkanHardwareLevel : AndroidFeature(PackageManager.FEATURE_VULKAN_HARDWARE_LEVEL)
    @RequiresApi(AndroidHelper.API_24)
    object VulkanHardwareVersion : AndroidFeature(PackageManager.FEATURE_VULKAN_HARDWARE_VERSION)
    object Watch : AndroidFeature(PackageManager.FEATURE_WATCH)
    object Webview : AndroidFeature(PackageManager.FEATURE_WEBVIEW)
    object Wifi : AndroidFeature(PackageManager.FEATURE_WIFI)
    @RequiresApi(AndroidHelper.API_26)
    object WifiAware : AndroidFeature(PackageManager.FEATURE_WIFI_AWARE)
    object WifiDirect : AndroidFeature(PackageManager.FEATURE_WIFI_DIRECT)
    @RequiresApi(AndroidHelper.API_27)
    object WifiPasspoint : AndroidFeature(PackageManager.FEATURE_WIFI_PASSPOINT)
    @RequiresApi(AndroidHelper.API_28)
    object WifiRtt : AndroidFeature(PackageManager.FEATURE_WIFI_RTT)

    val isAvailable: Boolean get() = ApplicationHelper.packageManager.hasSystemFeature(name)

}
