package me.shkschneider.skeleton.android.provider

import android.content.pm.PackageManager
import androidx.annotation.RequiresApi
import me.shkschneider.skeleton.android.os.AndroidHelper
import me.shkschneider.skeleton.android.app.ApplicationHelper

// <http://developer.android.com/reference/android/content/pm/PackageManager.html>
sealed class FeatureProvider(val name: String) {

    // Useless: only used to keep track of new features
    @RequiresApi(AndroidHelper.API_26)
    object ActivitiesOnSecondaryDisplays : FeatureProvider(PackageManager.FEATURE_ACTIVITIES_ON_SECONDARY_DISPLAYS)
    object AppWidgets : FeatureProvider(PackageManager.FEATURE_APP_WIDGETS)
    object AudioLowLatency : FeatureProvider(PackageManager.FEATURE_AUDIO_LOW_LATENCY)
    object AudioOutput : FeatureProvider(PackageManager.FEATURE_AUDIO_OUTPUT)
    object AudioPro : FeatureProvider(PackageManager.FEATURE_AUDIO_PRO)
    @RequiresApi(AndroidHelper.API_26)
    object Autofill : FeatureProvider(PackageManager.FEATURE_AUTOFILL)
    object Automotive : FeatureProvider(PackageManager.FEATURE_AUTOMOTIVE)
    object Backup : FeatureProvider(PackageManager.FEATURE_BACKUP)
    object Bluetooth : FeatureProvider(PackageManager.FEATURE_BLUETOOTH)
    object BluetoothLe : FeatureProvider(PackageManager.FEATURE_BLUETOOTH_LE)
    object Camera : FeatureProvider(PackageManager.FEATURE_CAMERA)
    object CameraAny : FeatureProvider(PackageManager.FEATURE_CAMERA_ANY)
    @RequiresApi(AndroidHelper.API_28)
    object CameraAr : FeatureProvider(PackageManager.FEATURE_CAMERA_AR)
    object CameraAutofocus : FeatureProvider(PackageManager.FEATURE_CAMERA_AUTOFOCUS)
    object CameraCapibilityManualPostProcessing : FeatureProvider(PackageManager.FEATURE_CAMERA_CAPABILITY_MANUAL_POST_PROCESSING)
    object CameraCapicilityManualSensor : FeatureProvider(PackageManager.FEATURE_CAMERA_CAPABILITY_MANUAL_SENSOR)
    object CameraCapabilityRaw : FeatureProvider(PackageManager.FEATURE_CAMERA_CAPABILITY_RAW)
    object CameraExternal : FeatureProvider(PackageManager.FEATURE_CAMERA_EXTERNAL)
    object CameraFlash : FeatureProvider(PackageManager.FEATURE_CAMERA_FLASH)
    object CameraFront : FeatureProvider(PackageManager.FEATURE_CAMERA_FRONT)
    object CameraLevelFull : FeatureProvider(PackageManager.FEATURE_CAMERA_LEVEL_FULL)
    @RequiresApi(AndroidHelper.API_28)
    object CompanionDeviceSetup : FeatureProvider(PackageManager.FEATURE_COMPANION_DEVICE_SETUP)
    object ConnectionService : FeatureProvider(PackageManager.FEATURE_CONNECTION_SERVICE)
    object ConsumerIr : FeatureProvider(PackageManager.FEATURE_CONSUMER_IR)
    object DeviceAdmin : FeatureProvider(PackageManager.FEATURE_DEVICE_ADMIN)
    @RequiresApi(AndroidHelper.API_26)
    object Embedded : FeatureProvider(PackageManager.FEATURE_EMBEDDED)
    @RequiresApi(AndroidHelper.API_24)
    object Ethermet : FeatureProvider(PackageManager.FEATURE_ETHERNET)
    @RequiresApi(AndroidHelper.API_29)
    object Face : FeatureProvider(PackageManager.FEATURE_FACE)
    object Faketouch : FeatureProvider(PackageManager.FEATURE_FAKETOUCH)
    object FaketouchMultitouchDistinct : FeatureProvider(PackageManager.FEATURE_FAKETOUCH_MULTITOUCH_DISTINCT)
    object FaketouchMultitouchJazzhand : FeatureProvider(PackageManager.FEATURE_FAKETOUCH_MULTITOUCH_JAZZHAND)
    object Fingerprint : FeatureProvider(PackageManager.FEATURE_FINGERPRINT)
    @RequiresApi(AndroidHelper.API_24)
    object FreeformWindowManagement : FeatureProvider(PackageManager.FEATURE_FREEFORM_WINDOW_MANAGEMENT)
    object Gamepad : FeatureProvider(PackageManager.FEATURE_GAMEPAD)
    object HifiSensors : FeatureProvider(PackageManager.FEATURE_HIFI_SENSORS)
    object HomeScreen : FeatureProvider(PackageManager.FEATURE_HOME_SCREEN)
    object InputMethods : FeatureProvider(PackageManager.FEATURE_INPUT_METHODS)
    @RequiresApi(AndroidHelper.API_29)
    object IpsecTunnels : FeatureProvider(PackageManager.FEATURE_IPSEC_TUNNELS)
    @RequiresApi(AndroidHelper.API_29)
    object Iris : FeatureProvider(PackageManager.FEATURE_IRIS)
    object Leanback : FeatureProvider(PackageManager.FEATURE_LEANBACK)
    @RequiresApi(AndroidHelper.API_26)
    object LeanbackOnly : FeatureProvider(PackageManager.FEATURE_LEANBACK_ONLY)
    object LiveTv : FeatureProvider(PackageManager.FEATURE_LIVE_TV)
    object LiveWallpaper : FeatureProvider(PackageManager.FEATURE_LIVE_WALLPAPER)
    object Location : FeatureProvider(PackageManager.FEATURE_LOCATION)
    object LocationGps : FeatureProvider(PackageManager.FEATURE_LOCATION_GPS)
    object LocationNetwork : FeatureProvider(PackageManager.FEATURE_LOCATION_NETWORK)
    object ManagedUsers : FeatureProvider(PackageManager.FEATURE_MANAGED_USERS)
    object Microphone : FeatureProvider(PackageManager.FEATURE_MICROPHONE)
    object Midi : FeatureProvider(PackageManager.FEATURE_MIDI)
    object Nfc : FeatureProvider(PackageManager.FEATURE_NFC)
    @RequiresApi(AndroidHelper.API_29)
    object NfcBeam : FeatureProvider(PackageManager.FEATURE_NFC_BEAM)
    object NfcHostCardEmulation : FeatureProvider(PackageManager.FEATURE_NFC_HOST_CARD_EMULATION)
    @RequiresApi(AndroidHelper.API_24)
    object NfcHostCardEmulationNfcf : FeatureProvider(PackageManager.FEATURE_NFC_HOST_CARD_EMULATION_NFCF)
    @RequiresApi(AndroidHelper.API_29)
    object NfcHostCardEmulationEse : FeatureProvider(PackageManager.FEATURE_NFC_OFF_HOST_CARD_EMULATION_ESE)
    @RequiresApi(AndroidHelper.API_29)
    object NfsOffHostCardEmulationUicc : FeatureProvider(PackageManager.FEATURE_NFC_OFF_HOST_CARD_EMULATION_UICC)
    object OpenglesExtensionPack : FeatureProvider(PackageManager.FEATURE_OPENGLES_EXTENSION_PACK)
    @RequiresApi(AndroidHelper.API_27)
    object Pc : FeatureProvider(PackageManager.FEATURE_PC)
    @RequiresApi(AndroidHelper.API_24)
    object PictureInPicture : FeatureProvider(PackageManager.FEATURE_PICTURE_IN_PICTURE)
    object Printing : FeatureProvider(PackageManager.FEATURE_PRINTING)
    @RequiresApi(AndroidHelper.API_27)
    object RawLow : FeatureProvider(PackageManager.FEATURE_RAM_LOW)
    @RequiresApi(AndroidHelper.API_27)
    object RamNormal : FeatureProvider(PackageManager.FEATURE_RAM_NORMAL)
    object ScreenLandscape : FeatureProvider(PackageManager.FEATURE_SCREEN_LANDSCAPE)
    object ScreenPortrait : FeatureProvider(PackageManager.FEATURE_SCREEN_PORTRAIT)
    object SecurelyRemovesUsers : FeatureProvider(PackageManager.FEATURE_SECURELY_REMOVES_USERS)
    @RequiresApi(AndroidHelper.API_29)
    object SecureLockScreen : FeatureProvider(PackageManager.FEATURE_SECURE_LOCK_SCREEN)
    object SensorAccelerometer : FeatureProvider(PackageManager.FEATURE_SENSOR_ACCELEROMETER)
    object SensorAmbientTemperature : FeatureProvider(PackageManager.FEATURE_SENSOR_AMBIENT_TEMPERATURE)
    object SensorBarometer : FeatureProvider(PackageManager.FEATURE_SENSOR_BAROMETER)
    object SensorCompass : FeatureProvider(PackageManager.FEATURE_SENSOR_COMPASS)
    object SensorGyroscope : FeatureProvider(PackageManager.FEATURE_SENSOR_GYROSCOPE)
    object SensorHeartRate : FeatureProvider(PackageManager.FEATURE_SENSOR_HEART_RATE)
    object SensorHeartRateEcg : FeatureProvider(PackageManager.FEATURE_SENSOR_HEART_RATE_ECG)
    object SensorLight : FeatureProvider(PackageManager.FEATURE_SENSOR_LIGHT)
    object SensorProximity : FeatureProvider(PackageManager.FEATURE_SENSOR_PROXIMITY)
    object SensorRelativeHumidity : FeatureProvider(PackageManager.FEATURE_SENSOR_RELATIVE_HUMIDITY)
    object SensorStepCounter : FeatureProvider(PackageManager.FEATURE_SENSOR_STEP_COUNTER)
    object SensorStepDetector : FeatureProvider(PackageManager.FEATURE_SENSOR_STEP_DETECTOR)
    object Sip : FeatureProvider(PackageManager.FEATURE_SIP)
    object SipVoip : FeatureProvider(PackageManager.FEATURE_SIP_VOIP)
    @RequiresApi(AndroidHelper.API_28)
    object StrongboxKeystore : FeatureProvider(PackageManager.FEATURE_STRONGBOX_KEYSTORE)
    object Telephony : FeatureProvider(PackageManager.FEATURE_TELEPHONY)
    object TelephonyCdma : FeatureProvider(PackageManager.FEATURE_TELEPHONY_CDMA)
    @RequiresApi(AndroidHelper.API_28)
    object TelephonyEuicc : FeatureProvider(PackageManager.FEATURE_TELEPHONY_EUICC)
    object TelephonyGsm : FeatureProvider(PackageManager.FEATURE_TELEPHONY_GSM)
    @RequiresApi(AndroidHelper.API_29)
    object TelephonyIms : FeatureProvider(PackageManager.FEATURE_TELEPHONY_IMS)
    @RequiresApi(AndroidHelper.API_28)
    object TelephonyMbms : FeatureProvider(PackageManager.FEATURE_TELEPHONY_MBMS)
    @Suppress("DEPRECATION")
    @Deprecated("Deprecated in Android.", ReplaceWith("FEATURE_LEANBACK"))
    object Television : FeatureProvider(PackageManager.FEATURE_TELEVISION)
    object Touchscreen : FeatureProvider(PackageManager.FEATURE_TOUCHSCREEN)
    object TouchscreenMultitouch : FeatureProvider(PackageManager.FEATURE_TOUCHSCREEN_MULTITOUCH)
    object TouchscreenMultitouchDistinct : FeatureProvider(PackageManager.FEATURE_TOUCHSCREEN_MULTITOUCH_DISTINCT)
    object TouchscreenMultitouchJazzhand : FeatureProvider(PackageManager.FEATURE_TOUCHSCREEN_MULTITOUCH_JAZZHAND)
    object UsbAccessory : FeatureProvider(PackageManager.FEATURE_USB_ACCESSORY)
    object UsbHost : FeatureProvider(PackageManager.FEATURE_USB_HOST)
    object VerifiedBoot : FeatureProvider(PackageManager.FEATURE_VERIFIED_BOOT)
    @RequiresApi(AndroidHelper.API_26)
    object VrHeadtracking : FeatureProvider(PackageManager.FEATURE_VR_HEADTRACKING)
    @RequiresApi(AndroidHelper.API_24)
    @Suppress("DEPRECATION")
    @Deprecated("Deprecated in Android.", ReplaceWith("FEATURE_VR_MODE_HIGH_PERFORMANCE"))
    object VrMode : FeatureProvider(PackageManager.FEATURE_VR_MODE)
    @RequiresApi(AndroidHelper.API_24)
    object BrModeHightPerformance : FeatureProvider(PackageManager.FEATURE_VR_MODE_HIGH_PERFORMANCE)
    @RequiresApi(AndroidHelper.API_26)
    object VulkanHardwareCompute : FeatureProvider(PackageManager.FEATURE_VULKAN_HARDWARE_COMPUTE)
    @RequiresApi(AndroidHelper.API_24)
    object VulkanHardwareLevel : FeatureProvider(PackageManager.FEATURE_VULKAN_HARDWARE_LEVEL)
    @RequiresApi(AndroidHelper.API_24)
    object VulkanHardwareVersion : FeatureProvider(PackageManager.FEATURE_VULKAN_HARDWARE_VERSION)
    object Watch : FeatureProvider(PackageManager.FEATURE_WATCH)
    object Webview : FeatureProvider(PackageManager.FEATURE_WEBVIEW)
    object Wifi : FeatureProvider(PackageManager.FEATURE_WIFI)
    @RequiresApi(AndroidHelper.API_26)
    object WifiAware : FeatureProvider(PackageManager.FEATURE_WIFI_AWARE)
    object WifiDirect : FeatureProvider(PackageManager.FEATURE_WIFI_DIRECT)
    @RequiresApi(AndroidHelper.API_27)
    object WifiPasspoint : FeatureProvider(PackageManager.FEATURE_WIFI_PASSPOINT)
    @RequiresApi(AndroidHelper.API_28)
    object WifiRtt : FeatureProvider(PackageManager.FEATURE_WIFI_RTT)

    val isAvailable: Boolean get() = ApplicationHelper.packageManager.hasSystemFeature(name)

}
